version: "0.1"
user: mohitsaini
key: LT_hMA1DfBUke1LtVmnk7FCjQh8S4RxZoEaD5zprdD2tLUnNzo
testSuites: []
pre: [npm install]
preDirectives:
    commands: [npm install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
jobLabel:
    - wdio
    - selenium
    - mac
    - autosplit
runson: mac
autosplit: true
concurrency: 2
testDiscovery:
    autosubset: true
    command: grep -lr 'describe' tests/specs/*.js
    mode: dynamic
    type: raw
testRunnerCommand: npx wdio conf/wdio.conf.js --spec $test
globalTimeout: 90
tunnel: "false"
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
jobID: 6190ed72-1584-4f8a-820f-947362a0be88
codeDirectory: WebdriverIO-HyperExecute-Sample
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: null
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: ""
    name: ""
    type: default
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    cache: false
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
slackChannel: ""
whiteLabelProductTag: ""
